"""Ejemplos didácticos etiquetados a mano; no son datos reales de clientes."""

DATOS_ENTRENAMIENTO = [
    ('Quiero conocer el precio del producto', 'VENTAS'),
    ('Deseo comprar uno de sus servicios', 'VENTAS'),
    ('Necesito información sobre precios y promociones', 'VENTAS'),
    ('Quisiera contratar el servicio', 'VENTAS'),
    ('Necesito ayuda con el servicio', 'SOPORTE'),
    ('Tengo un problema técnico', 'SOPORTE'),
    ('El sistema no funciona correctamente', 'SOPORTE'),
    ('Necesito soporte para solucionar un error', 'SOPORTE'),
    ('La atención demoró demasiado', 'RECLAMO'),
    ('Estoy inconforme con el servicio', 'RECLAMO'),
    ('No solucionaron mi problema', 'RECLAMO'),
    ('El servicio fue muy malo', 'RECLAMO'),
    ('Cuál es el horario de atención', 'CONSULTA'),
    ('Dónde se encuentra la empresa', 'CONSULTA'),
    ('Quisiera obtener más información', 'CONSULTA'),
    ('Tengo una consulta sobre sus servicios', 'CONSULTA'),
    ('La atención fue excelente', 'FELICITACION'),
    ('El servicio fue muy rápido', 'FELICITACION'),
    ('Estoy muy satisfecho con la atención', 'FELICITACION'),
    ('Excelente trabajo del equipo', 'FELICITACION'),
    ('Gracias por la información', 'OTROS'),
    ('Buen día', 'OTROS'),
    ('Saludos a todo el equipo', 'OTROS'),
    ('Mensaje general para la empresa', 'OTROS'),
    ('Busco una cotización para comprar varios productos', 'VENTAS'),
    ('Quiero contratar un plan mensual', 'VENTAS'),
    ('Qué promociones tienen para clientes nuevos', 'VENTAS'),
    ('Necesito presupuesto para renovar el servicio', 'VENTAS'),
    ('No puedo acceder a mi cuenta', 'SOPORTE'),
    ('Cómo recupero mi contraseña', 'SOPORTE'),
    ('La aplicación muestra un error al iniciar', 'SOPORTE'),
    ('Necesito ayuda para configurar el sistema', 'SOPORTE'),
    ('La entrega llegó tarde y el producto estaba roto', 'RECLAMO'),
    ('Cobro incorrecto quiero un reembolso', 'RECLAMO'),
    ('El servicio es malo y la atención mala', 'RECLAMO'),
    ('Estoy decepcionado no cumplieron lo prometido', 'RECLAMO'),
    ('Atienden los domingos en la oficina', 'CONSULTA'),
    ('Dónde puedo consultar el horario', 'CONSULTA'),
    ('Cuál es la dirección de la sucursal', 'CONSULTA'),
    ('Qué documentos debo presentar', 'CONSULTA'),
    ('Los felicito por su excelente servicio', 'FELICITACION'),
    ('Gracias resolvieron mi problema rápidamente', 'FELICITACION'),
    ('Muy buena atención recomiendo la empresa', 'FELICITACION'),
    ('Todo salió perfecto estoy contento', 'FELICITACION'),
    ('Hola equipo', 'OTROS'),
    ('Adjunto el archivo solicitado', 'OTROS'),
    ('Les envío mis datos de contacto', 'OTROS'),
    ('Este es un mensaje de prueba', 'OTROS'),
]

DATOS_SENTIMIENTO = [
    ('La atención fue excelente', 'POSITIVO'),
    ('Estoy muy satisfecho con el servicio', 'POSITIVO'),
    ('Muchas gracias por la ayuda', 'POSITIVO'),
    ('El equipo hizo un buen trabajo', 'POSITIVO'),
    ('El servicio fue rápido y eficiente', 'POSITIVO'),
    ('Me atendieron muy bien', 'POSITIVO'),
    ('La atención fue pésima', 'NEGATIVO'),
    ('Estoy molesto con el servicio', 'NEGATIVO'),
    ('No solucionaron mi problema', 'NEGATIVO'),
    ('El sistema funciona muy mal', 'NEGATIVO'),
    ('Demoraron demasiado en atenderme', 'NEGATIVO'),
    ('Estoy inconforme con la atención', 'NEGATIVO'),
    ('Quiero conocer el horario de atención', 'NEUTRAL'),
    ('Necesito información sobre sus servicios', 'NEUTRAL'),
    ('Cuál es el precio del producto', 'NEUTRAL'),
    ('Deseo comunicarme con la empresa', 'NEUTRAL'),
    ('Quisiera realizar una consulta', 'NEUTRAL'),
    ('Dónde se encuentra su oficina', 'NEUTRAL'),
    ('El servicio es bueno', 'POSITIVO'),
    ('La atención es buena', 'POSITIVO'),
    ('El producto es excelente', 'POSITIVO'),
    ('La entrega fue puntual', 'POSITIVO'),
    ('Todo salió perfecto', 'POSITIVO'),
    ('Estoy contento con el resultado', 'POSITIVO'),
    ('Resolvieron el problema rápidamente', 'POSITIVO'),
    ('Recomiendo esta empresa', 'POSITIVO'),
    ('No fue malo el servicio', 'POSITIVO'),
    ('La atención no fue mala', 'POSITIVO'),
    ('No estoy molesto', 'POSITIVO'),
    ('No tuve problemas', 'POSITIVO'),
    ('El paquete llegó completo y en buenas condiciones. Gracias por cumplir lo prometido.', 'POSITIVO'),
    ('Me ayudaron con paciencia y resolvieron mis dudas. Estoy satisfecho con el resultado.', 'POSITIVO'),
    ('El servicio es malo', 'NEGATIVO'),
    ('La atención es mala', 'NEGATIVO'),
    ('El producto es pésimo', 'NEGATIVO'),
    ('La entrega fue tardía', 'NEGATIVO'),
    ('Todo salió mal', 'NEGATIVO'),
    ('Estoy decepcionado con el resultado', 'NEGATIVO'),
    ('No resolvieron el problema', 'NEGATIVO'),
    ('No recomiendo esta empresa', 'NEGATIVO'),
    ('No fue bueno el servicio', 'NEGATIVO'),
    ('La atención no fue buena', 'NEGATIVO'),
    ('No estoy satisfecho', 'NEGATIVO'),
    ('Nunca recibí respuesta', 'NEGATIVO'),
    ('El paquete llegó roto y tarde. Nadie respondió a mi reclamo y quiero un reembolso.', 'NEGATIVO'),
    ('Me cobraron dos veces y no devolvieron el dinero. Estoy molesto por la demora.', 'NEGATIVO'),
    ('Solicito una cotización', 'NEUTRAL'),
    ('Adjunto mis documentos', 'NEUTRAL'),
    ('Cuál es la dirección', 'NEUTRAL'),
    ('Atienden los domingos', 'NEUTRAL'),
    ('Quiero actualizar mis datos', 'NEUTRAL'),
    ('Envío el comprobante solicitado', 'NEUTRAL'),
    ('Tengo una pregunta sobre el contrato', 'NEUTRAL'),
    ('Cuánto cuesta el envío', 'NEUTRAL'),
    ('Hola buenos días', 'NEUTRAL'),
    ('El pedido tiene tres productos', 'NEUTRAL'),
    ('Necesito cambiar la fecha de entrega', 'NEUTRAL'),
    ('Dónde consulto mi factura', 'NEUTRAL'),
    ('Quisiera saber si atienden los sábados. También necesito conocer los documentos para registrarme.', 'NEUTRAL'),
    ('Estoy comparando sus planes. Por favor envíen el precio mensual y las condiciones del contrato.', 'NEUTRAL'),
]

