-- Ejecutar en Supabase SQL Editor. Conserva biometria_facial y sus muestras.
BEGIN;
CREATE TABLE IF NOT EXISTS public.app_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_email VARCHAR(254) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL CHECK (length(trim(nombre)) > 0),
    password_hash TEXT NOT NULL,
    rol TEXT NOT NULL DEFAULT 'Trabajador' CHECK (rol IN ('Administrador', 'Trabajador')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    session_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (usuario_email = lower(trim(usuario_email)))
);
-- -1 invalida las sesiones del sistema anterior. El nuevo login escribe la versión actual.
ALTER TABLE public.auth_sessions ADD COLUMN IF NOT EXISTS usuario_version INTEGER NOT NULL DEFAULT -1;
ALTER TABLE public.app_usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biometria_facial ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.app_usuarios, public.biometria_facial FROM anon, authenticated;
COMMIT;
-- auth_sessions y biometria_facial conservan usuario_email; no se renombra el correo.
-- La conexión privada del backend debe estar autorizada para trabajar con RLS activo.
